swagger: "2.0"
info:
  version: "1.0.0"
  title: UFOLEP Badminton API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /teams:
    # binds a127 app logic to a route
    x-swagger-router-controller: teams
    get:
      description: Returns 'Teams' to the caller
      # used as the method name of the controller
      operationId: getTeams
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TeamsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create a new team to the list
      operationId: createTeam
      parameters:
        - name: team
          description: Team properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Team"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /teams/{id}:
    x-swagger-router-controller: teams
    get:
      description: Get a team
      operationId: getTeam
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TeamResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
    put:
      description: Update a team
      operationId: updateTeam
      parameters:
        - name: id
          description: Team id
          type: string
          in: path
          required: true
        - name: team
          description: Team properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Team"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete a team
      operationId: deleteTeam
      parameters:
        - name: id
          description: Team id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /matchs:
    # binds a127 app logic to a route
    x-swagger-router-controller: matchs
    get:
      description: Returns 'Matchs' to the caller
      # used as the method name of the controller
      operationId: getMatchs
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MatchsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create a new match to the list
      operationId: createMatch
      parameters:
        - name: match
          description: Match properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Match"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
  /matchs/{id}:
    x-swagger-router-controller: matchs
    get:
      description: Get a match
      operationId: getMatch
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MatchResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
    put:
      description: Update a match
      operationId: updateMatch
      parameters:
        - name: id
          description: Match id
          type: string
          in: path
          required: true
        - name: match
          description: Match properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Match"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete a match
      operationId: deleteMatch
      parameters:
        - name: id
          description: Match id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Team:
    properties:
        name:
          type: string
        players: 
          type: array
          items:
            type: object
            properties:
              icon: 
                type: string
              firstname:
                type: string
              lastname:
                type: string
              email: 
                type: string
              phone:
                type: string
              isCaptain:
                type: boolean
            required:
              - firstname
              - lastname
              - email
              - phone
              - isCaptain
        place:
          type: object
          properties:
            name:
              type: string
            location:
              type: object
              properties:
                type: 
                  type: string
                coordinates:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                  required:
                    - latitude
                    - longitude
                category:
                  type: string
              required:
                - type
                - coordinates
                - category
            schedule:
              type: array
              items:
                type: object
                properties:
                  day:
                    type: string
                  start:
                    type: string
                  end:
                    type: string  
                required:
                  - day
                  - start
                  - end
          required:
            - name
            - location
            - schedule
    required:
      - name
      - players
      - place
  TeamResponse:
    properties:
        _id:
          type: string
        name:
          type: string
        players: 
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              icon: 
                type: string
              firstname:
                type: string
              lastname:
                type: string
              email: 
                type: string
              phone:
                type: string
              isCaptain:
                type: boolean
            required:
              - firstname
              - lastname
              - email
              - phone
              - isCaptain
        place:
          type: object
          properties:
            name:
              type: string
            location:
              type: object
              properties:
                type: 
                  type: string
                coordinates:
                  type: object
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                  required:
                    - latitude
                    - longitude
                category:
                  type: string
              required:
                - type
                - coordinates
                - category
            schedule:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                  day:
                    type: string
                  start:
                    type: string
                  end:
                    type: string
                required:
                - _id
                - day
                - start
                - end
          required:
            - name
            - location
            - schedule
    required:
      - _id
      - name
      - players
      - place      
  TeamsResponse:
    required:
      - teams
    properties:
      teams:
        type: array
        items:
          type: object
          properties:
            _id:
              type: string
            name:
              type: string
            players: 
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                  icon: 
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email: 
                    type: string
                  phone:
                    type: string
                  isCaptain:
                    type: boolean
                required:
                  - firstname
                  - lastname
                  - email
                  - phone
                  - isCaptain
            place:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: object
                  properties:
                    type: 
                      type: string
                    coordinates:
                      type: object
                      properties:
                        latitude:
                          type: number
                        longitude:
                          type: number
                      required:
                        - latitude
                        - longitude
                    category:
                      type: string
                  required:
                    - type
                    - coordinates
                    - category
                schedule:
                  type: array
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                      day:
                        type: string
                      start:
                        type: string
                      end:
                        type: string      
                    required:
                      - _id
                      - day
                      - start
                      - end
              required:
                - name
                - location
                - schedule
          required:
            - _id
            - name
            - players
            - place
  Match:
    properties:
        season:
          type: number
        gender:
          type: string
        division: 
          type: number
        pools:
          type: string
        day:
          type: object
          properties:
            id: 
              type: string
            start_date:
              type: string
            end_date:
              type: string
          required:
            - id
            - start_date
            - end_date
        schedule_date:
          type: string
        local: 
          type: string
        visitor:
          type: string
        local_score:
          type: number
        visitor_score:
          type: number
        base64MatchSheetImage:
          type: string
        base64ReceiptImage:
          type: string
    required:
      - season
      - gender
      - division
      - pools
      - day
      - local
      - visitor
  MatchResponse:
    properties:
      _id:
        type: string
      season:
        type: number
      gender:
        type: string
      division: 
        type: number
      pools:
        type: string
      day:
        type: object
        properties:
          id: 
            type: string
          start_date:
            type: string
          end_date:
            type: string
        required:
          - id
          - start_date
          - end_date
      schedule_date:
        type: string
      local: 
        type: string
      visitor:
        type: string
      local_score:
        type: number
      visitor_score:
        type: number
      base64MatchSheetImage:
        type: string
      base64ReceiptImage:
          type: string
    required:
      - _id
      - season
      - gender
      - division
      - pools
      - day
      - local
      - visitor    
  MatchsResponse:
    required:
      - matchs
    properties:
      matchs:
        type: array
        items:
          type: object
          properties:
            _id:
              type: string
            season:
              type: number
            gender:
              type: string
            division: 
              type: number
            pools:
              type: string
            day:
              type: object
              properties:
                id: 
                  type: string
                start_date:
                  type: string
                end_date:
                  type: string
              required:
                - id
                - start_date
                - end_date
            schedule_date:
              type: string
            local: 
              type: string
            visitor:
              type: string
            local_score:
              type: number
            visitor_score:
              type: number
            base64MatchSheetImage:
              type: string
            base64ReceiptImage:
                type: string
          required:
            - _id
            - season
            - gender
            - division
            - pools
            - day
            - local
            - visitor  
  GeneralResponse:
    type: object
    properties:
      success:
        type: boolean
        description: returns true if successful
      description:
        type: string
        description: a short operation comment 
    required:
      - success
      - description
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
